In [4]:
import numpy as np
import pandas as pd


ratings = pd.read_csv('MyFoodRatings.csv')
ratings =ratings.drop('Name',axis = 1)
ratings
u, s, vt = np.linalg.svd(ratings, full_matrices=True)

In [9]:
u.shape

(12, 12)

In [10]:
vt.shape

(9, 9)

In [13]:
s

array([1.27279221e+01, 1.05770379e+01, 8.84826058e+00, 1.24205263e+00,
       1.06125858e+00, 4.06927550e-01, 3.87210908e-16, 3.62597321e-16,
       0.00000000e+00])

In [14]:
u

array([[-6.80413817e-01,  3.02164435e-17, -1.54169932e-17,
         3.08339864e-17,  7.55411086e-17, -2.60871753e-16,
        -2.26654487e-01, -4.08248290e-01, -5.44331054e-01,
        -2.65393249e-03, -1.50554312e-01, -5.30786497e-03],
       [-5.44331054e-01,  9.78791554e-18, -4.99397711e-18,
         9.98795423e-18,  2.44697888e-17, -8.45033496e-17,
        -7.34194605e-02, -1.32242558e-01,  8.23676589e-01,
        -8.59679831e-04, -4.87685749e-02, -1.71935966e-03],
       [-4.08248290e-01,  7.34093665e-18, -3.74548283e-18,
         7.49096567e-18,  1.83523416e-17, -6.33775122e-17,
        -5.50645954e-02,  9.00818081e-01, -1.32242558e-01,
        -6.44759873e-04, -3.65764312e-02, -1.28951975e-03],
       [-2.72165527e-01, -1.06128345e-16,  5.41486614e-17,
        -1.08297323e-16, -2.65320862e-16,  9.16252350e-16,
         7.96072032e-01, -6.61212792e-02, -8.81617055e-02,
         9.32133069e-03,  5.28787576e-01,  1.86426614e-02],
       [ 0.00000000e+00, -3.26217015e-01, -7.6668220

In [16]:
ratings

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         4       4       4         0            0     0      0      0   
2         3       3       3         0            0     0      0      0   
3         2       2       2         0            0     0      0      0   
4         0       0       0         2            2     2      0      0   
5         0       0       0         1            1     1      0      0   
6         0       0       0         5            3     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      2      2   
9         0       0       0         0            0     0      1      1   
10        0       0       0         0            0     0      3      4   
11        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [20]:
np.array(vt)

array([[-0.57735027, -0.57735027, -0.57735027,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.63787511, -0.51226147,
        -0.57506829,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.47616345, -0.55763787, -0.67993263],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.29611035,  0.62638051, -0.72108676],
       [-0.        , -0.        , -0.        ,  0.65303038, -0.75559349,
        -0.05128155,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.        , -0.        ,  0.        ,  0.        ,
         0.        ,  0.82800183, -0.54469025, -0.13313715],
       [ 0.        ,  0.        ,  0.        , -0.40824829, -0.40824829,
         0.81649658,  0.        ,  0.        ,  0.        ],
       [-0.81649658,  0.40824829,  0.40824829, -0.        , -0

In [25]:
data = pd.read_csv('FoodRatings_all_same_5.csv')
data = data.drop('Name',axis = 1)
u, s, VT = np.linalg.svd(data, full_matrices=True)


In [26]:
s

array([17.32050808, 17.32050808, 17.32050808,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [27]:

data = pd.read_csv('FoodRatings_all_same_5_4_3.csv')
data = data.drop('Name',axis = 1)
u, s, VT = np.linalg.svd(data, full_matrices=True)

In [28]:
s

array([17.32050808, 13.85640646, 10.39230485,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])